version: '3.8'

services:
  postgres:
    restart: always
    container_name: f1-api-db
    image: postgres
    environment:
      POSTGRES_DB: f1-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
